# SKILL TRACK - Python Fundamentals

## Introduction to Python

##### Hello Python! 

In [2]:
a,b = 10,5
ress1 = a/b
print(ress1)
type(ress1)

2.0


float

In [3]:
c,d = 2.2,2
ress2 = c/d
print(ress2)
type(ress2)

1.1


float

In [4]:
one = 'adinda2'
print(type(one))

<class 'str'>


In [5]:
dua = True
print(type(dua))

<class 'bool'>


In [6]:
x1 = 'ab'
x2 = 'cd'
ress3 = x1+x2
print(type(ress3))

<class 'str'>


##### Python List

In [7]:
#can contain different types
l1 = ['joni', 12, 'alex', 15, 'lowa', 12]
print(type(l1))
print(l1)

<class 'list'>
['joni', 12, 'alex', 15, 'lowa', 12]


In [8]:
l2=[['jakarta', 13000],
   ['bandung', 10000],
   ['medan', 9000]]
print(l2)

[['jakarta', 13000], ['bandung', 10000], ['medan', 9000]]


In [9]:
l3=[1,2,3,4,5,6,7]
print(l3[-1])
print(l3[-2])
print(l3[:])
print(l3[:3])
print(l3[5:])

7
6
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3]
[6, 7]


In [10]:
#----changing list element
l4=[1,2,3,4,5,6,7]
l4[0]=1000
print(l4)

l5=['adinda', 'dana', 'lowi', 'andre']
l5[0:2]=['none', 'none'] #nilai penggantinya harus sebanyak list yg diganti
print(l5)

l6=['adinda', 'dana', 'lowi', 'andre']
l6[0:2]='nono'
print('hasil dari mengedit list yang salah: ',l6)

[1000, 2, 3, 4, 5, 6, 7]
['none', 'none', 'lowi', 'andre']
hasil dari mengedit list yang salah:  ['n', 'o', 'n', 'o', 'lowi', 'andre']


In [11]:
#---- adding and removing element
l7=['a','b','c','d','eaaa']

del(l7[-1])
print(l7)

l8=[1,2,3,4,5]
l8 + [10,11] #tidak berhasil adding elements
print(l8)
newl8 = l8 + [10,11]
print(newl8)

['a', 'b', 'c', 'd']
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 10, 11]


##### Functions

In [12]:
l9 = [10, 11, 12 ,13, 14, 15, 20]
print(max(l8), min(l8))

5 1


In [13]:
round(10.1)

10

In [14]:
round(10.9)

11

In [15]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [16]:
round(10.45, 1)

10.4

In [17]:
round(10.46, 1)

10.5

In [18]:
round(10.46, 2)

10.46

In [19]:
round(10.45, 2)

10.45

In [20]:
#----Method
# method is a function that belong to object
# object with type str have methods like capitalize(), raplace() and so on
# object with type list have methods like index(), count()

l10 = [10,11,12,13, 11, 11, 12]
l10.index(13)
l10.count(11)

3

In [21]:
#----List of String Method
s1='america'
s1else='usa'
print(s1.capitalize(), s1else.upper())

America USA


In [22]:
s2='JAPAN'
s2else='HIRAGANA'
print(s2.casefold(), s2else.lower())

japan hiragana


In [23]:
s3='Spain'
s3.center(20)

'       Spain        '

In [24]:
s4='Jane lives in USA. Jane is going to Bali'
s4.count('Jane')

2

In [25]:
s5='INDOENSIA'
s5.find('I')

0

In [26]:
s6='LOKASI'
s6.index('A')

3

In [27]:
s7='Jumlah penduduk adalah 100 juta jiwa'
s7.isalnum()

False

In [28]:
s8='kompas gramedia'
s9='kompasgramedia'
print(s8.isalpha(), s9.isalpha())

False True


In [29]:
#----Packeges
# import numpy as np
# from numpy import array

##### Numpy 

In [30]:
# Numpy is a numeric python
# Numpy array is the alternative to python list
# numpay can calculate the entire array using simple command

In [31]:
import numpy as np

In [32]:
r = np.array([10, 5, 7])
kel_lingkaran = 3.14*r*2
luas_lingkaran = 3.14*r**2
print('Keliling lingkaran: ',kel_lingkaran)
print('Luas lingkaran: ', luas_lingkaran)

Keliling lingkaran:  [62.8  31.4  43.96]
Luas lingkaran:  [314.    78.5  153.86]


In [33]:
ar1=np.array([1,2,3,4,5])
ar2=np.array([5,4,3,2,1])
print(ar1+ar2)
# tanda + akan bermakna beda anatara object list dan numpy array
# tanda + pd list akan menyambungkan dua list menjadi satu
# tanda + pd numpy array menjumlahkan isi numpy array a dengan b
# dan menyimpan hasilnya di numpay array yang baru

[6 6 6 6 6]


In [34]:
diffar=ar1-ar2
print(diffar)
print(diffar>0) # array of bolean
print(diffar[diffar>0]) # the actual result

[-4 -2  0  2  4]
[False False False  True  True]
[2 4]


In [46]:
#----2D Numpy Array
ad = np.array([[10,11,12,13,14,15],
                [20,21,22,23,24,25]])
print(type(ad))
ad

<class 'numpy.ndarray'>


array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [47]:
ad[0] #subsetting array

array([10, 11, 12, 13, 14, 15])

In [48]:
ad[0][0]

10

In [56]:
ac= np.array([[1,1,1,1,1],
             [2,2,2,2,2],
             [3,3,3,3,3],
             [4,4,4,4,4]])
ac

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [65]:
ac[2:, 2:]

array([[3, 3, 3],
       [4, 4, 4]])

In [68]:
ac[:2, :2]

array([[1, 1],
       [2, 2]])

In [69]:
ac[1:4, 1:4]

array([[2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [49]:
ad[:, 0]

array([10, 20])

In [51]:
#array operation
print(np.mean(ad[0]))
print(np.median(ad[0]))

12.5
12.5


## Intermediate Python

##### Basic plots with matplotlib

In [71]:
import matplotlib.pyplot as plt
import pandas as pd

In [92]:
usshooting = pd.read_csv('shootings.csv')
usshooting.head()

id                name        date   manner_of_death       armed   age  \
0   3          Tim Elliot  2015-01-02              shot         gun  53.0   
1   4    Lewis Lee Lembke  2015-01-02              shot         gun  47.0   
2   5  John Paul Quintero  2015-01-03  shot and Tasered     unarmed  23.0   
3   8     Matthew Hoffman  2015-01-04              shot  toy weapon  32.0   
4   9   Michael Rodriguez  2015-01-04              shot    nail gun  39.0   

  gender      race           city state  signs_of_mental_illness threat_level  \
0      M     Asian        Shelton    WA                     True       attack   
1      M     White          Aloha    OR                    False       attack   
2      M  Hispanic        Wichita    KS                    False        other   
3      M     White  San Francisco    CA                     True       attack   
4      M  Hispanic          Evans    CO                    False       attack   

          flee  body_camera          arms_category  
0  Not fleeing        False                   Guns  
1  Not fleeing        False                   Guns  
2  Not fleeing        False                Unarmed  
3  Not fleeing        False  Other unusual objects  
4  Not fleeing        False       Piercing objects

In [123]:
type(usshooting)

pandas.core.frame.DataFrame

In [145]:
dat = usshooting[(usshooting['date']<'2021') &( usshooting['date']>'2019')]
#print(dat['gender'=='M'].count())
dat

id                        name        date   manner_of_death  \
3663  4334         Dylan Michael Smith  2019-01-01              shot   
3664  4504      Brandon Lovell Webster  2019-01-01              shot   
3665  4342           Matthew Burroughs  2019-01-02              shot   
3666  4343             Abdoulaye Thiam  2019-01-02              shot   
3667  4345        Arron Thomas Lambert  2019-01-02              shot   
3668  4344               Samuel Garcia  2019-01-03              shot   
3669  4347                Robert Myers  2019-01-03              shot   
3670  4348              Joseph Roberts  2019-01-03              shot   
3671  4349    Abiel Innis De Joel Rios  2019-01-03              shot   
3672  4350            Jae Wesley Hardy  2019-01-03              shot   
3673  4505       Eric David Sauerhagen  2019-01-03              shot   
3674  4367             Zonell Williams  2019-01-04              shot   
3675  4506          Jeremy Dean Duncan  2019-01-04              shot   
3676  4507        John Richard Camacho  2019-01-04              shot   
3677  4508       Lawrence Thompson III  2019-01-04              shot   
3678  4355            Oliver Hernandez  2019-01-05              shot   
3679  4357             Adolfo Gonzalez  2019-01-05              shot   
3680  4360      David John Engebretson  2019-01-05              shot   
3681  4361               Shaun Kennedy  2019-01-05              shot   
3682  4352          Kevin Shawn Hanson  2019-01-06              shot   
3683  4353             Andre C. Gladen  2019-01-06  shot and Tasered   
3684  5409                   Nil Houer  2019-01-06              shot   
3685  4351         Miguel Barraza-Lugo  2019-01-07              shot   
3686  4362                 David Novak  2019-01-07              shot   
3687  4510         Jeremy Dale Edmonds  2019-01-07              shot   
3688  4368           Johnny Lee Burney  2019-01-10              shot   
3689  4374             Geoffrey Morris  2019-01-10              shot   
3690  4366               Juston Landry  2019-01-11              shot   
3691  4379       Treshun Symone Miller  2019-01-11              shot   
3692  4381  Charles Frederick Landeros  2019-01-11              shot   
...    ...                         ...         ...               ...   
4865  5844       Heba Momtaz Al-Azhari  2020-05-29              shot   
4866  5845                       TK TK  2020-05-29              shot   
4867  5848                       TK TK  2020-05-29              shot   
4868  5850         Momodou Lamin Sisay  2020-05-29              shot   
4869  5879             Jarvis Sullivan  2020-05-29              shot   
4870  5863            Derrick Thompson  2020-05-30              shot   
4871  5852                Israel Berry  2020-05-31              shot   
4872  5878            Thomas Sutherlin  2020-05-31  shot and Tasered   
4873  5842                David McAtee  2020-06-01              shot   
4874  5866                 Jorge Gomez  2020-06-01              shot   
4875  5867           Ryan Emblem Moore  2020-06-01              shot   
4876  5896             Sean Monterrosa  2020-06-02              shot   
4877  5897              Tyquarn Graves  2020-06-02              shot   
4878  5898               Mary Lawrence  2020-06-03              shot   
4879  5902         Gregory W. Hallback  2020-06-03              shot   
4880  5904              Eric A. Galvan  2020-06-03              shot   
4881  5905       Scott Anderson Hutton  2020-06-03              shot   
4882  5903            Benjamin Ballard  2020-06-05              shot   
4883  5899               Kamal Flowers  2020-06-06              shot   
4884  5900                Erik Salgado  2020-06-06              shot   
4885  5908                Jarrid Hurst  2020-06-07              shot   
4886  5911                Lewis Ruffin  2020-06-09              shot   
4887  5913        Gregorio Cruz Vanloo  2020-06-11              shot   
4888  5914            Mason James Lira  2020-06-

## Python Data Science Toolbox (Part 1) 

## Python Data Science Toolbox (Part 2) 